# Generated by Django 4.2.26 on 2025-12-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandlestickCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, help_text='数据源: binance, okx, tradingview等', max_length=20)),
                ('symbol', models.CharField(db_index=True, help_text='交易对: BTC-USDT', max_length=20)),
                ('bar', models.CharField(db_index=True, help_text='时间周期: 1m, 5m, 1H, 1D等', max_length=10)),
                ('time', models.BigIntegerField(db_index=True, help_text='K线时间戳(秒)')),
                ('open', models.DecimalField(decimal_places=8, help_text='开盘价', max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, help_text='最高价', max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, help_text='最低价', max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, help_text='收盘价', max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, help_text='成交量', max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='缓存时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'verbose_name': 'K线缓存',
                'verbose_name_plural': 'K线缓存',
                'db_table': 'candlestick_cache',
                'ordering': ['time'],
                'indexes': [models.Index(fields=['source', 'symbol', 'bar', 'time'], name='candlestick_source_733bc6_idx'), models.Index(fields=['source', 'symbol', 'bar', '-time'], name='candlestick_source_e4b5e6_idx')],
                'unique_together': {('source', 'symbol', 'bar', 'time')},
            },
        ),
    ]
