# Generated by ChatGPT on 2025-12-07
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candlestickcache',
            name='mode',
            field=models.CharField(db_index=True, default='spot', help_text='交易模式: spot/contract', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='candlestickcache',
            unique_together={('source', 'symbol', 'mode', 'bar', 'time')},
        ),
        migrations.RemoveIndex(
            model_name='candlestickcache',
            name='candlestick_source_733bc6_idx',
        ),
        migrations.RemoveIndex(
            model_name='candlestickcache',
            name='candlestick_source_e4b5e6_idx',
        ),
        migrations.AddIndex(
            model_name='candlestickcache',
            index=models.Index(fields=['source', 'symbol', 'mode', 'bar', 'time'], name='cstick_src_mode_time_idx'),
        ),
        migrations.AddIndex(
            model_name='candlestickcache',
            index=models.Index(fields=['source', 'symbol', 'mode', 'bar', '-time'], name='cstick_src_mode_desc_idx'),
        ),
    ]
