# Generated by Django 4.2.30 on 2026-07-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candlestickcache_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='OKXAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="用户命名，如'只读Key'", max_length=64)),
                ('api_key', models.CharField(help_text='OKX API Key', max_length=128, unique=True)),
                ('encrypted_secret_key', models.BinaryField(help_text='Fernet 加密的 Secret Key')),
                ('encrypted_passphrase', models.BinaryField(help_text='Fernet 加密的 Passphrase')),
                ('passphrase_hash', models.CharField(help_text='bcrypt 哈希（用于登陆校验）', max_length=256)),
                ('account_info', models.JSONField(blank=True, help_text='注册时拉取的账户信息缓存', null=True)),
                ('note', models.CharField(blank=True, default='', help_text='权限备注(只读/交易/网格等)', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'OKX 账户',
                'verbose_name_plural': 'OKX 账户',
                'db_table': 'okx_account',
            },
        ),
    ]
