# Generated by Django 4.2.30 on 2026-07-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_okxaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='okxaccount',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='是否为模拟盘(OKX Demo)'),
        ),
    ]
