# Generated by Django 4.2.30 on 2026-07-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_strategy_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, help_text='数据源: binance, okx', max_length=20)),
                ('symbol', models.CharField(db_index=True, help_text='交易对: BTCUSDT', max_length=20)),
                ('granularity', models.CharField(default='8h', help_text='粒度: 8h', max_length=10)),
                ('timestamp', models.BigIntegerField(db_index=True, help_text='资金费率时间戳(秒)')),
                ('funding_rate', models.DecimalField(decimal_places=12, help_text='资金费率', max_digits=20)),
                ('realized_rate', models.DecimalField(blank=True, decimal_places=12, help_text='实际结算费率', max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='缓存时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'verbose_name': '资金费率历史',
                'verbose_name_plural': '资金费率历史',
                'db_table': 'funding_rate_history',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['source', 'symbol', 'granularity', '-timestamp'], name='frh_src_sym_gran_ts_desc')],
                'unique_together': {('source', 'symbol', 'granularity', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='BasisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, help_text='数据源: binance, okx', max_length=20)),
                ('symbol', models.CharField(db_index=True, help_text='交易对: BTCUSDT', max_length=20)),
                ('contract_type', models.CharField(default='perpetual', help_text='合约类型: perpetual', max_length=20)),
                ('granularity', models.CharField(default='1h', help_text='粒度: 1h, 1d', max_length=10)),
                ('timestamp', models.BigIntegerField(db_index=True, help_text='基差时间戳(秒)')),
                ('basis', models.DecimalField(decimal_places=8, help_text='基差', max_digits=20)),
                ('basis_rate', models.DecimalField(decimal_places=6, help_text='基差率(%)', max_digits=10)),
                ('contract_price', models.DecimalField(decimal_places=8, help_text='合约价格', max_digits=20)),
                ('spot_price', models.DecimalField(decimal_places=8, help_text='现货价格', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='缓存时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'verbose_name': '基差历史',
                'verbose_name_plural': '基差历史',
                'db_table': 'basis_history',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['source', 'symbol', 'contract_type', 'granularity', '-timestamp'], name='bh_src_sym_ct_gra_ts_desc')],
                'unique_together': {('source', 'symbol', 'contract_type', 'granularity', 'timestamp')},
            },
        ),
    ]
